services:
  app-monitor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: monitor-sistema
    
    # TRUQUE DE MESTRE: Rodar com o mesmo ID do usuário do host (1000:1000)
    # Isso resolve permissões de arquivo e erros de 'ownership' do Git
    user: "1000:1000"
    
    volumes:
      - ../:/app
    
    environment:
      - PROJECT_NAME=MonitorDocker
      - ENV_TYPE=dev-container
      - ENABLE_CPU_STATS=true
      - ENABLE_MEM_STATS=true
      - ENABLE_DISK_STATS=true
      # Para o Git não reclamar que não tem nome configurado dentro do container
      - GIT_AUTHOR_NAME=Monitor Bot
      - GIT_AUTHOR_EMAIL=bot@monitor.local
      - GIT_COMMITTER_NAME=Monitor Bot
      - GIT_COMMITTER_EMAIL=bot@monitor.local
